// <auto-generated />
using System;
using LicenciaMedica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicenciaMedica.Migrations
{
    [DbContext(typeof(LicenciaMedicaContext))]
    [Migration("20221023030406_CreateLicenciaMedicaDB")]
    partial class CreateLicenciaMedicaDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Licencia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpleadoID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinSolicitada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioSolicitada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicoID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("EmpleadoID");

                    b.HasIndex("MedicoID");

                    b.ToTable("Licencias");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Prestadora", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelefonoContactoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TelefonoContactoID");

                    b.ToTable("Prestadoras");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Telefono", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("TipoDeTelefono")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("num")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Usuario", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FechaAlta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Empleado", b =>
                {
                    b.HasBaseType("_2022_2C_I_LicenciaMedica.Models.Usuario");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmpleadoActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("EmpleadoRRHH")
                        .HasColumnType("bit");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObraSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Empleado");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Medico", b =>
                {
                    b.HasBaseType("_2022_2C_I_LicenciaMedica.Models.Usuario");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestadoraID")
                        .HasColumnType("int");

                    b.HasIndex("PrestadoraID");

                    b.HasDiscriminator().HasValue("Medico");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Licencia", b =>
                {
                    b.HasOne("_2022_2C_I_LicenciaMedica.Models.Empleado", "Empleado")
                        .WithMany("Licencias")
                        .HasForeignKey("EmpleadoID");

                    b.HasOne("_2022_2C_I_LicenciaMedica.Models.Medico", "Medico")
                        .WithMany("Licencias")
                        .HasForeignKey("MedicoID");

                    b.Navigation("Empleado");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Prestadora", b =>
                {
                    b.HasOne("_2022_2C_I_LicenciaMedica.Models.Telefono", "TelefonoContacto")
                        .WithMany()
                        .HasForeignKey("TelefonoContactoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelefonoContacto");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Telefono", b =>
                {
                    b.HasOne("_2022_2C_I_LicenciaMedica.Models.Usuario", null)
                        .WithMany("Telefonos")
                        .HasForeignKey("UsuarioID");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Medico", b =>
                {
                    b.HasOne("_2022_2C_I_LicenciaMedica.Models.Prestadora", "Prestadora")
                        .WithMany("Medicos")
                        .HasForeignKey("PrestadoraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestadora");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Prestadora", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Usuario", b =>
                {
                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Empleado", b =>
                {
                    b.Navigation("Licencias");
                });

            modelBuilder.Entity("_2022_2C_I_LicenciaMedica.Models.Medico", b =>
                {
                    b.Navigation("Licencias");
                });
#pragma warning restore 612, 618
        }
    }
}
